title: "Bioactives Initiative Africa"
description: "Bioactives initiative Africa is a research group focused on mining African biodiversity to discover important bioactive molecules"
url:"https://biafrica.github.io/"
theme: jekyll-theme-minimal  # Change based on your theme
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
